# Requisição de login
# @name login
POST https://agro-delivery-management.vercel.app/auth/login
content-type: application/json

{
    "email": "admin@email.com",
    "password": "123456"
}


###

@token= {{login.response.body.$.access_token}}

###

POST https://agro-delivery-management.vercel.app/maintenance
content-type: application/json
Authorization: Bearer {{token}}

{
        "truck": "68191c89d4e0db39f5c52f5b",
        "maintenanceType": "Preventiva",
        "description": "Descrição da manutenção",
        "maintenanceDate": "2025-05-06",
        "nextScheduledDate": "2025-11-06",
        "cost": 100,
        "status": "Em andamento",
        "comments": "Comentários da manutenção"
}

###

GET https://agro-delivery-management.vercel.app/maintenance
Authorization: Bearer {{token}}

###

PATCH https://agro-delivery-management.vercel.app/maintenance/68191a28d4e0db39f5c52f58
content-type: application/json
Authorization: Bearer {{token}}

{
    "nextReview": "2025-05-01",
    "maintenanceCost": 250
}

###

GET https://agro-delivery-management.vercel.app/maintenance/68191a28d4e0db39f5c52f58
Authorization: Bearer {{token}}

###

DELETE  https://agro-delivery-management.vercel.app/maintenance/68191a28d4e0db39f5c52f58
Authorization: Bearer {{token}}

###